name: Register Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: <<&PROMPT>>
        required: true
jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
