name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
    inputs:
      lookback:
        default: "3"
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == '{{{TRIGGER}}}'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: {{{TOKEN}}}
          {{#SSH}}
          # For commits that modify workflow files: SSH key enables tagging, but
          # releases require manual creation. For full automation of such commits,
          # use a PAT with `workflow` scope instead of GITHUB_TOKEN.
          # See: https://github.com/JuliaRegistries/TagBot#commits-that-modify-workflow-files
          ssh: {{{SSH}}}
          {{/SSH}}
          {{#SSH_PASSWORD}}
          ssh_password: {{{SSH_PASSWORD}}}
          {{/SSH_PASSWORD}}
          {{#CHANGELOG}}
          changelog: {{{CHANGELOG}}}
          {{/CHANGELOG}}
          {{#CHANGELOG_IGNORE}}
          changelog_ignore: {{{CHANGELOG_IGNORE}}}
          {{/CHANGELOG_IGNORE}}
          {{#GPG}}
          gpg: {{{GPG}}}
          {{/GPG}}
          {{#GPG_PASSWORD}}
          gpg_password: {{{GPG_PASSWORD}}}
          {{/GPG_PASSWORD}}
          {{#REGISTRY}}
          registry: {{{REGISTRY}}}
          {{/REGISTRY}}
          {{#BRANCHES}}
          branches: {{{BRANCHES}}}
          {{/BRANCHES}}
          {{#DISPATCH}}
          dispatch: {{{DISPATCH}}}
          {{/DISPATCH}}
          {{#DISPATCH_DELAY}}
          dispatch_delay: {{{DISPATCH_DELAY}}}
          {{/DISPATCH_DELAY}}
