# Documentation: https://github.com/JuliaCI/Appveyor.jl
environment:
  matrix:
{{#VERSIONS}}
    - julia_version: {{{.}}}
{{/VERSIONS}}
platform:
{{#PLATFORMS}}
  - {{{.}}}
{{/PLATFORMS}}
cache:
  - '%USERPROFILE%\.julia\artifacts'
{{#HAS_ALLOW_FAILURES}}
matrix:
  allow_failures:
{{#ALLOW_FAILURES}}
    - julia_version: {{{.}}}
{{/ALLOW_FAILURES}}
{{/HAS_ALLOW_FAILURES}}
branches:
  only:
    - master
    - /release-.*/
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
{{#HAS_CODECOV}}
on_success:
  - echo "%JL_CODECOV_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
{{/HAS_CODECOV}}
