name: CompatHelper
on:
  schedule:
    - cron: '0 0 * * *'  # Everyday at midnight
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install CompatHelper
        run: using Pkg; Pkg.add("CompatHelper")
        shell: julia --color=yes {0}
      - name: Run CompatHelper
        run: using CompatHelper; CompatHelper.main()
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
